# Site
name: "माता धाई वृद्धि मन्दिर"
description: "A Hindu Temple in Pyuthan Nepal."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "https-dhaimata-org"
email: "dhaibriddhi@gmail.com"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  sal:
    name: Sal
    site: https://www.wowthemes.net
    avatar: https://dhaimata.org/assets/images/avatar1.jpg
    bio: "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    email: wowthemesnet@gmail.com
    twitter: https://twitter.com/wowthemesnet

  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: https://dhaimata.org/assets/images/avatar2.jpg
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet

  npdulal:
    name: ज्यो.पण्डित नारायण प्रसाद दुलाल
    site: https://www.hamropatro.com
    avatar: https://images.hamro-files.com/gas7Hn9J6gUA063SwAfCzp3nAIQ=/50x50/smart/http://storage.googleapis.com/hamropatro-storage/assets/hamropatro.com/images/abd2ca35-36b2-4bb2-b834-fa7fc371b610.jpg
    bio: "ज्योतिष, पण्डित"
    email: fb.me/narayan.dulal
    twitter: https://www.facebook.com/narayan.dulal
  
  sthakuri:
    name: sthakuri
    site: https://www.sthakuri.com
    avatar: https://dhaimata.org/assets/images/avatar1.jpg
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: hello@sthakuri.com
    twitter: https://twitter.com/itsmesuvash

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
